#!/bin/bash

# initially use `nbstripout --install` to register nbstripout for the repository

# only run for lines which match /nbstripout/
# replace ^#* with either nothing (to enable) or a single #

ATTR=.git/info/attributes

if [ "$1" == "enable" ]; then
    sed -i '/nbstripout/ s/^#*//' "$ATTR"
elif [ "$1" == "disable" ]; then
    sed -i '/nbstripout/ s/^#*/#/' "$ATTR"
else
    echo "usage: toggle-nbstripout (enable|disable)"
fi

echo "current state of attribute file \"$ATTR\":"
cat "$ATTR"
